### ISSUE TITLE
MCP Server regression in agents@0.1.2

### ISSUE THREAD

**Issue by kentcdodds** [cloudflare/agents#456]
Loom walkthrough: https://www.loom.com/share/0308cdfa98d04e8f839b0d0aab80eb53

Here are some logs when I try to use [this server](https://github.com/kentcdodds/cloudflare-no-init-mcp) in [Goose (by Block)](https://block.github.io/goose/):

Starting with agents@0.1.1:

```sh
~/Desktop/cloudflare-no-init-mcp (main) 👽
$ npm run dev

> remote-mcp-server-authless@0.0.0 dev
> wrangler dev


 ⛅️ wrangler 4.35.0
───────────────────
Your Worker has access to the following bindings:
Binding                     Resource            Mode
env.MCP_OBJECT (MyMCP)      Durable Object      local

╭──────────────────────────────────────────────────────────────────────╮
│  [b] open a browser [d] open devtools [c] clear console [x] to exit  │
╰──────────────────────────────────────────────────────────────────────╯
⎔ Starting local server...
[wrangler:info] Ready on http://localhost:8787
State updated
Connection established
Connection W3XLlYl387HVeVnlPhNP5 connected to _a:a8fec08aa309c5e6dad7db4c38d8b210e069829f705c9a1d131692ef66038c90
[wrangler:info] POST /mcp 200 OK (14ms)
Connection established
Connection fQZ8Ofj9KtgEyp1jMshW1 connected to _a:a8fec08aa309c5e6dad7db4c38d8b210e069829f705c9a1d131692ef66038c90
[wrangler:info] POST /mcp 202 Accepted (1ms)
[wrangler:info] GET /mcp 405 Method Not Allowed (0ms)
[wrangler:info] DELETE /mcp 405 Method Not Allowed (3ms)
State updated
Connection established
Connection AEzKG_bs1uYJWQ8z7JsG5 connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 200 OK (8ms)
Connection established
Connection 2lpLSX3qG6oSaMRt0Nae6 connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 202 Accepted (2ms)
[wrangler:info] GET /mcp 405 Method Not Allowed (1ms)
Connection established
Connection WP_CYY79jkBAI89IZ_LOt connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 200 OK (2ms)
Connection established
Connection PMD_M7oQNthe-F30bzxiN connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 200 OK (1ms)
Connection established
Connection AJC3DhsKVZ-fw-ws5bV-D connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 200 OK (2ms)
Connection established
Connection QKJ06YjQ6dHdfKXUXmO_f connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 200 OK (3ms)
Connection established
Connection o0fsFojcQ_rF5AEIRjxFy connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 200 OK (2ms)
Connection established
Connection fLrXeYC4KBm0Umcy54QNh connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 200 OK (1ms)
Connection established
Connection 6tGLFigJALX4DXh3gtp-x connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 200 OK (3ms)
Connection established
Connection leZ-wlgo_ZgmvNO2mIdjY connected to _a:eacb8ad58f917ae5ae7930e2465f3cc0d0ec6991abcaa1f041fd524767d1cddf
[wrangler:info] POST /mcp 200 OK (1ms)
⎔ Shutting down local server...
```

Everything's working ok (though the Method Not Allowed on DELETE is unexpected).

Then I upgrade to agents@0.1.2 and I get this:

```sh
~/Desktop/cloudflare-no-init-mcp (main) 👽
$ npm i

changed 1 package in 446ms
~/Desktop/cloudflare-no-init-mcp (main) 👽
$ npm run dev

> remote-mcp-server-authless@0.0.0 dev
> wrangler dev


 ⛅️ wrangler 4.35.0
───────────────────
Your Worker has access to the following bindings:
Binding                     Resource            Mode
env.MCP_OBJECT (MyMCP)      Durable Object      local

╭──────────────────────────────────────────────────────────────────────╮
│  [b] open a browser [d] open devtools [c] clear console [x] to exit  │
╰──────────────────────────────────────────────────────────────────────╯
⎔ Starting local server...
[wrangler:info] Ready on http://localhost:8787
[wrangler:info] DELETE /mcp 204 No Content (19ms)
✘ [ERROR] Uncaught Error: destroyed 


Connection established
[wrangler:info] POST /mcp 200 OK (12ms)
Connection established
[wrangler:info] POST /mcp 202 Accepted (1ms)
[wrangler:info] GET /mcp 400 Bad Request (1ms)
✘ [ERROR] Uncaught Error: destroyed 


[wrangler:info] DELETE /mcp 204 No Content (4ms)
✘ [ERROR] Error closing SSE connection: TypeError: This WritableStream has been closed.

      at onClose
  (file:///Users/kentcdodds/Desktop/cloudflare-no-init-mcp/node_modules/agents/src/mcp/utils.ts:319:28)
      at null.<anonymous>
  (file:///Users/kentcdodds/Desktop/cloudflare-no-init-mcp/node_modules/agents/src/mcp/utils.ts:324:11)


✘ [ERROR] Uncaught Error: destroyed 


✘ [ERROR] Uncaught Error: destroyed 


Connection established
[wrangler:info] POST /mcp 200 OK (8ms)
Connection established
[wrangler:info] POST /mcp 202 Accepted (3ms)
[wrangler:info] GET /mcp 400 Bad Request (0ms)
✘ [ERROR] Error closing SSE connection: TypeError: This WritableStream has been closed.

      at onClose
  (file:///Users/kentcdodds/Desktop/cloudflare-no-init-mcp/node_modules/agents/src/mcp/utils.ts:319:28)
      at null.<anonymous>
  (file:///Users/kentcdodds/Desktop/cloudflare-no-init-mcp/node_modules/agents/src/mcp/utils.ts:324:11)


✘ [ERROR] Uncaught Error: destroyed 


[wrangler:info] DELETE /mcp 204 No Content (4ms)
✘ [ERROR] Uncaught Error: destroyed 


✘ [ERROR] Uncaught Error: destroyed 

```

I've only noticed this with Goose, so it's probably something funny it's doing with the connection, but this was handled gracefully before and it is no longer handled gracefully so I think the fix is probably in the agents side of things.

**Comment by kentcdodds** [comment]
I don't know if this will be helpful at all, but I handed this off to cursor to analyze the commit and here's what it gave me:

I'll analyze the commit to understand what changes might have caused these errors. Let me first examine the commit and then look at the relevant code.


[1 tool called]

Now let me look at the specific MCP utils file that's mentioned in the error to understand the issue:


[1 tool called]

Let me also look at the broader context around this area to understand the WebSocket handling:


[1 tool called]

Now let me look at the commit changes more carefully to understand what was added. Let me search for the specific changes in the commit:


[1 tool called]

Let me look at the specific changes to the utils.ts file to understand what was added:


[1 tool called]

Now let me look at the current state of the utils.ts file to see if there are any differences:


[1 tool called]

Let me also check the GET handler section to see the standalone SSE implementation:


[1 tool called]

Now let me look at the error more closely. The error is happening at line 319 in the `onClose` function. Let me check if there are any race conditions or multiple close calls:


[1 tool called]

Now I can see the issue! Let me analyze the problem:

## Analysis of the Error

Based on the commit changes and the error logs, I can identify several potential culprits for the "destroyed" and "This WritableStream has been closed" errors:

### **Primary Culprit: Race Condition in Writer Close Operations**

The main issue is in the **POST handler** of the `createStreamingHttpHandler` function. There are **multiple places where `writer.close()` is called**, creating a race condition:

1. **Line 292-295**: In the `onMessage` handler when all responses are received:
   ```typescript
   if (requestIds.size === 0) {
     ws?.close();
     await writer.close(); // First close
   }
   ```

2. **Line 307**: In the `onError` handler:
   ```typescript
   await writer.close(); // Second close
   ```

3. **Line 319**: In the `onClose` handler:
   ```typescript
   await writer.close(); // Third close
   ```

4. **Line 338**: For notifications/responses only:
   ```typescript
   ws.close(); // This triggers the onClose handler above
   ```

### **The Race Condition Scenario**

When a WebSocket connection closes (either normally or due to an error), **multiple event handlers can fire simultaneously**:

1. The `onMessage` handler might detect that all responses are received and call `writer.close()`
2. Simultaneously, the `onClose` handler fires and also tries to call `writer.close()`
3. The second call to `writer.close()` fails with "This WritableStream has been closed"

### **Secondary Issues**

1. **Inconsistent Error Handling**: The `onError` handler ignores errors when closing, but the `onClose` handler logs them, leading to inconsistent behavior.

2. **Missing Guard Conditions**: There's no check to see if the writer is already closed before attempting to close it.

3. **WebSocket Close Triggers**: When `ws.close()` is called on line 338, it immediately triggers the `onClose` event handler, which then tries to close an already-closed writer.

### **The "destroyed" Error**

The "destroyed" error likely comes from the WebSocket connection being closed while there are still pending operations, or from the Durable Object being destroyed while connections are still active.

## **Recommended Fixes**

1. **Add a guard to prevent multiple close calls**:
   ```typescript
   let writerClosed = false;
   const safeCloseWriter = async () => {
     if (!writerClosed) {
       writerClosed = true;
       await writer.close();
     }
   };
   ```

2. **Consolidate close logic** to ensure only one close operation happens.

3. **Add proper error handling** for WebSocket close operations.

4. **Review the flow** for notifications/responses to ensure the WebSocket close doesn't trigger unnecessary writer close operations.

The commit introduced a complex WebSocket-to-SSE forwarding mechanism with multiple event handlers that can race against each other, leading to these connection management errors.

**Comment by deathbyknowledge** [comment]
Hey @kentcdodds, I've had a look at the errors and there were a few different issues at play here:

- The `TypeError: This WritableStream has been closed` error would happen on client disconnect, which in some cases our handler would try to close the writer twice from different event listeners. We should handle that gracefully, which is addressed here #467

- The issue with Goose not being able to read the tools seems to be on their end. As you can see in the logs, their client is trying to establish the standalone stream through the `GET` request but the server returns **400**. That's because the client is not including the session ID (`mcp-session-id` header) that the server returns after initialization. 
Seems like they're not expecting to get a **400** and the client just fails. I tried testing it by hardcoding the session ID on the `McpAgent` side so the `GET` doesn't fail and Goose read the tools correctly then.

- The `Uncaught Error: destroyed` is caused by the `DELETE`, which calls `.destroy()` for the `McpAgent` with a given session ID. This wipes all storage + resets the DO.
Internally, the reset is caused by calling [abort](https://developers.cloudflare.com/durable-objects/api/state/#abort), which throws an uncatchable error that will show in your logs.

**Comment by whoiskatrin** [comment]
@kentcdodds are we good with the resolution on this one?

**Comment by kentcdodds** [comment]
Unfortunately no. With agents@0.1.3 I'm still getting:

> Error closing SSE connection: TypeError: This WritableStream has been closed.

Incidentally I'm also getting:

> OAuth error response: 401 invalid_token - Missing or invalid access token

I'm not certain why that is, but the WritableStream error may be a culprit

**Comment by kentcdodds** [comment]
Additionally, I think the Uncaught Error should probably be handled as well.

**Comment by whoiskatrin** [comment]
> Unfortunately no. With agents@0.1.3 I'm still getting:
> 
> > Error closing SSE connection: TypeError: This WritableStream has been closed.
> 
> Incidentally I'm also getting:
> 
> > OAuth error response: 401 invalid_token - Missing or invalid access token
> 
> I'm not certain why that is, but the WritableStream error may be a culprit

That's correct, the merged changes aren't released yet, so you'd need to try with @beta instead. We will try to do another release this week.

**Comment by threepointone** [comment]
@kentcdodds if you can test the @beta release, we can do an immediate release

**Comment by kentcdodds** [comment]
Confirmed that `@beta` has eliminated these issues 👍 Thanks!

**Comment by threepointone** [comment]
Awesome, just released 0.1.4
